--- 玩家建造者
TPL_UNIT.Builder = UnitTpl("Peasant", "avatar")
    :preAbility({ TPL_ABILITY.Build })
    :name("伟大的建造者")
    :model("Peasant")
    :icon("ReplaceableTextures\\CommandButtons\\BTNPeasant.blp")
    :move(522)
    :attack(10)
    :assault(Assault({ mode = "missile", model = "GuardTowerMissile", homing = true, height = 100, speed = 800 }))
    :attackSpaceBase(1.5)
    :attackRange(600)
    :hp(100)
    :modelScale(1.2)
    :scale(1.2)